// This file was automatically generated by:
//  /nfs/s-l011/local/vol02/p/parthghosh/SlicerExecutionModel/SEM-build/GenerateCLP/bin/GenerateCLP --InputXML /nfs/s-l011/local/vol02/p/parthghosh/hw04-iampartho/src/DOG/DOG.xml --OutputCxx /nfs/s-l011/local/vol02/p/parthghosh/hw04-iampartho/hw04-build/src/DOG/DOGCLP.h
//
#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <string>
#include <vector>
#include <map>

#include <sstream>

#include "tclap/CmdLine.h"
#include "ModuleProcessInformation.h"

#ifdef _WIN32
#define Module_EXPORT __declspec(dllexport)
#elif defined(MODULE_HIDDEN_VISIBILITY)
#define Module_EXPORT __attribute__((visibility("default")))
#else
#define Module_EXPORT
#endif

#if defined(main) && !defined(REGISTER_TEST)
// If main defined as a preprocessor symbol, redefine it to the expected entry point.
#undef main
#define main ModuleEntryPoint

extern "C" {
  Module_EXPORT char *GetXMLModuleDescription();
  Module_EXPORT int ModuleEntryPoint(int, char*[]);
}
#endif

extern "C" {
Module_EXPORT char XMLModuleDescription[] = 
"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
"<executable>\n"
"    <category>MIATT.HW04.parthghosh</category>\n"
"    <title>Difference of Gaussians (DOG) Edge Filter</title>\n"
"    <description>\n"
"        Computes DOG(f) = G_sigma1(f) - G_sigma2(f) to produce an edge-enhanced image.\n"
"        The output is rescaled so that the minimum maps to 0 and the maximum maps to 255,\n"
"        and stored as an unsigned char NIFTI image. sigma1 != sigma2; typically sigma2 > sigma1.\n"
"        ECE:5490 HW04 — Partho Ghosh\n"
"    </description>\n"
"    <version>1.0.0</version>\n"
"    <documentation-url>https://itk.org/ITKSoftwareGuide/html/Book2/ITKSoftwareGuide-Book2.html</documentation-url>\n"
"    <license>Apache 2.0</license>\n"
"    <contributor>Partho Ghosh (ECE:5490 HW04)</contributor>\n"
"    <acknowledgements> Developed as part of ECE:5490 Multi-Dimensional Image Analysis Tools, Spring 2026, University of Iowa. Course instructor: Professor Hans Johnson. This work uses the Insight Toolkit (ITK), an open-source library for medical image analysis developed by the National Library of Medicine (NLM) and the Insight Software Consortium (ISC). Slicer Execution Model (SEM) developed by Kitware Inc. and the Slicer community (slicer.org). For understanding and help with the coding and writing Claude.ai has been used.</acknowledgements>\n"
"\n"
"    <parameters>\n"
"        <label>Filter Parameters</label>\n"
"        <description>Sigma values for the two Gaussian filters.</description>\n"
"\n"
"        <double>\n"
"            <name>sigma1</name>\n"
"            <longflag>sigma1</longflag>\n"
"            <description>Sigma for the first (narrower) Gaussian. Must differ from sigma2.</description>\n"
"            <label>Sigma 1</label>\n"
"            <default>1.0</default>\n"
"            <constraints>\n"
"                <minimum>0.001</minimum>\n"
"                <maximum>50.0</maximum>\n"
"                <step>0.1</step>\n"
"            </constraints>\n"
"        </double>\n"
"\n"
"        <double>\n"
"            <name>sigma2</name>\n"
"            <longflag>sigma2</longflag>\n"
"            <description>Sigma for the second (wider) Gaussian. Must differ from sigma1. Typically sigma2 > sigma1.</description>\n"
"            <label>Sigma 2</label>\n"
"            <default>2.0</default>\n"
"            <constraints>\n"
"                <minimum>0.001</minimum>\n"
"                <maximum>50.0</maximum>\n"
"                <step>0.1</step>\n"
"            </constraints>\n"
"        </double>\n"
"\n"
"    </parameters>\n"
"\n"
"    <parameters>\n"
"        <label>IO</label>\n"
"        <description>Input/output parameters</description>\n"
"        <image>\n"
"            <name>inputVolume</name>\n"
"            <longflag>inputVolume</longflag>\n"
"            <label>Input Volume</label>\n"
"            <channel>input</channel>\n"
"            <description>3D NIFTI input image.</description>\n"
"        </image>\n"
"        <image>\n"
"            <name>outputVolume</name>\n"
"            <longflag>outputVolume</longflag>\n"
"            <label>Output Volume</label>\n"
"            <channel>output</channel>\n"
"            <description>DOG edge-enhanced output image (unsigned char, range 0-255).</description>\n"
"        </image>\n"
"    </parameters>\n"
"\n"
"</executable>\n"
"\n"
;

}

void
splitString (const std::string &text,
             const std::string &separators,
             std::vector<std::string> &words)
{
  const std::string::size_type n = text.length();
  std::string::size_type start = text.find_first_not_of(separators);
  while (start < n)
    {
    std::string::size_type stop = text.find_first_of(separators, start);
    if (stop > n) stop = n;
    words.push_back(text.substr(start, stop - start));
    start = text.find_first_not_of(separators, stop+1);
    }
}

void
splitFilenames (const std::string &text,
                std::vector<std::string> &words)
{
  const std::string::size_type n = text.length();
  bool quoted;
  std::string comma(",");
  std::string quote("\"");
  std::string::size_type start = text.find_first_not_of(comma);
  while (start < n)
    {
    quoted = false;
    std::string::size_type startq = text.find_first_of(quote, start);
    std::string::size_type stopq = text.find_first_of(quote, startq+1);
    std::string::size_type stop = text.find_first_of(comma, start);
    if (stop > n) stop = n;
    if (startq != std::string::npos && stopq != std::string::npos)
      {
      while (startq < stop && stop < stopq && stop != n)
         {
         quoted = true;
         stop = text.find_first_of(comma, stop+1);
         if (stop > n) stop = n;
         }
      }
    if (!quoted)
      {
      words.push_back(text.substr(start, stop - start));
      }
    else
      {
      words.push_back(text.substr(start+1, stop - start-2));
      }
    start = text.find_first_not_of(comma, stop+1);
    }
}

char *GetXMLModuleDescription()
{
   return XMLModuleDescription;
}

#define GENERATE_LOGO
#define GENERATE_XML \
  if (argc >= 2 && (strcmp(argv[1],"--xml") == 0)) \
    { \
    std::cout << GetXMLModuleDescription(); \
    return EXIT_SUCCESS; \
    }
#define GENERATE_DECLARE \
    /* These two vectors are used to store the JSON deserialized value */ \
    /* that are then compiled with the command line. */ \
    std::vector< std::string > deserializedVectorFlaggedArgs; \
    std::vector< std::string > deserializedVectorPositionalArgs; \
    /* This map is used to store the JSON deserialized value of multiple args*/ \
    /* where the key is the argument flag and the value the values of each arg. */ \
    std::map< std::string, std::vector<std::string> > deserializedMultipleArgsMap; \
 \
    /* This vector is used to look up if a flag requires an argument after it. */ \
    /* This is used to differentiate between: */ \
    /* ./myExec --boolFlag /my/first/arg */ \
    /* ./myExec --flag flagArg */ \
    std::vector< std::string > nonbooleanFlags; \
    nonbooleanFlags.emplace_back("--sigma1"); \
    nonbooleanFlags.emplace_back("--sigma2"); \
    nonbooleanFlags.emplace_back("--inputVolume"); \
    nonbooleanFlags.emplace_back("--outputVolume"); \
    nonbooleanFlags.emplace_back("--processinformationaddress"); \
    nonbooleanFlags.emplace_back("--returnparameterfile"); \
    /* This map use is twofold: */ \
    /*  - to find whether a flag is multiple */ \
    /*  - to know if we need to reset the multiple arg value because it was */ \
    /*    in the JSON and it's also in the command line. */ \
    std::map<std::string, bool> multipleFlags; \
    double sigma1 = 1.0; \
    double sigma2 = 2.0; \
    std::string inputVolume; \
    std::string outputVolume; \
    bool echoSwitch = false; \
    bool xmlSwitch = false; \
    std::string processInformationAddressString = "0"; \
    std::string returnParameterFile; \

#define GENERATE_TCLAP_PARSE \
    std::string fullDescription("Description: "); \
    fullDescription += "\n        Computes DOG(f) = G_sigma1(f) - G_sigma2(f) to produce an edge-enhanced image.\n        The output is rescaled so that the minimum maps to 0 and the maximum maps to 255,\n        and stored as an unsigned char NIFTI image. sigma1 != sigma2; typically sigma2 > sigma1.\n        ECE:5490 HW04 — Partho Ghosh\n"; \
    if (!std::string("Partho Ghosh (ECE:5490 HW04)").empty()) \
      { \
      fullDescription += "\nAuthor(s): Partho Ghosh (ECE:5490 HW04)"; \
      } \
    if (!std::string("Developed as part of ECE:5490 Multi-Dimensional Image Analysis Tools, Spring 2026, University of Iowa. Course instructor: Professor Hans Johnson. This work uses the Insight Toolkit (ITK), an open-source library for medical image analysis developed by the National Library of Medicine (NLM) and the Insight Software Consortium (ISC). Slicer Execution Model (SEM) developed by Kitware Inc. and the Slicer community (slicer.org). For understanding and help with the coding and writing Claude.ai has been used.").empty()) \
      { \
      fullDescription += "\nAcknowledgements: Developed as part of ECE:5490 Multi-Dimensional Image Analysis Tools, Spring 2026, University of Iowa. Course instructor: Professor Hans Johnson. This work uses the Insight Toolkit (ITK), an open-source library for medical image analysis developed by the National Library of Medicine (NLM) and the Insight Software Consortium (ISC). Slicer Execution Model (SEM) developed by Kitware Inc. and the Slicer community (slicer.org). For understanding and help with the coding and writing Claude.ai has been used."; \
      } \
    TCLAP::CmdLine commandLine (fullDescription, \
       ' ', \
      "1.0.0" ); \
 \
      std::ostringstream msg; \
    msg.str("");msg << "Sigma for the first (narrower) Gaussian. Must differ from sigma2. (value: " << sigma1 << ")"; \
    TCLAP::ValueArg<double > sigma1Arg("", "sigma1", msg.str(), false, sigma1, "double", commandLine); \
 \
    msg.str("");msg << "Sigma for the second (wider) Gaussian. Must differ from sigma1. Typically sigma2 > sigma1. (value: " << sigma2 << ")"; \
    TCLAP::ValueArg<double > sigma2Arg("", "sigma2", msg.str(), false, sigma2, "double", commandLine); \
 \
    msg.str("");msg << "3D NIFTI input image.";    TCLAP::ValueArg<std::string > inputVolumeArg("", "inputVolume", msg.str(), false, inputVolume, "std::string", commandLine); \
 \
    msg.str("");msg << "DOG edge-enhanced output image (unsigned char, range 0-255).";    TCLAP::ValueArg<std::string > outputVolumeArg("", "outputVolume", msg.str(), false, outputVolume, "std::string", commandLine); \
 \
    msg.str("");msg << "Echo the command line arguments (value: " << echoSwitch << ")"; \
    TCLAP::SwitchArg echoSwitchArg("", "echo", msg.str(), commandLine, echoSwitch); \
 \
    msg.str("");msg << "Produce xml description of command line arguments (value: " << xmlSwitch << ")"; \
    TCLAP::SwitchArg xmlSwitchArg("", "xml", msg.str(), commandLine, xmlSwitch); \
 \
    msg.str("");msg << "Address of a structure to store process information (progress, abort, etc.). (value: " << processInformationAddressString << ")"; \
    TCLAP::ValueArg<std::string > processInformationAddressStringArg("", "processinformationaddress", msg.str(), false, processInformationAddressString, "std::string", commandLine); \
 \
    msg.str("");msg << "Filename in which to write simple return parameters (int, float, int-vector, etc.) as opposed to bulk return parameters (image, geometry, transform, measurement, table).";    TCLAP::ValueArg<std::string > returnParameterFileArg("", "returnparameterfile", msg.str(), false, returnParameterFile, "std::string", commandLine); \
 \
try \
  { \
    /* Build a map of flag aliases to the true flag */ \
    std::map<std::string,std::string> flagAliasMap; \
    std::map<std::string,std::string> deprecatedFlagAliasMap; \
    std::map<std::string,std::string> longFlagAliasMap; \
    std::map<std::string,std::string> deprecatedLongFlagAliasMap; \
 \
    /* Go through argc and consolidate the JSON with the parameters from the command line */ \
    /* In case of conflict, take the command line. */ \
    auto dvOptionnalArgsIt = deserializedVectorFlaggedArgs.begin(); \
    size_t noFlagCounter = 0; \
    size_t ac = 1; \
 \
    while (ac < static_cast<size_t>(argc)) \
      { \
      /* short flag case && long flag case */ \
       if ((strlen(argv[ac]) == 2 && argv[ac][0]=='-') \
           || (strlen(argv[ac]) > 2 && argv[ac][0]=='-' && argv[ac][1]=='-')) \
         { \
         std::string flag = argv[ac]; \
         /* Remap the flag if necessary */ \
         if (strlen(argv[ac]) == 2) \
           { \
           /* Short flag remapping */ \
           auto ait = flagAliasMap.find(flag); \
           auto dait = deprecatedFlagAliasMap.find(flag); \
           if (ait != flagAliasMap.end()) \
             { \
             /* remap the flag */ \
             flag = (*ait).second; \
             } \
           else if (dait != deprecatedFlagAliasMap.end()) \
             { \
             std::cout << "Flag \"" << flag << "\" is deprecated. Please use flag \"" << (*dait).second << "\" instead. " << std::endl; \
             /* remap the flag */ \
             flag = (*dait).second; \
             } \
           } \
         else \
           { \
           /* Long flag remapping */ \
           auto ait = longFlagAliasMap.find(flag); \
           auto dait = deprecatedLongFlagAliasMap.find(flag); \
           if (ait != longFlagAliasMap.end()) \
             { \
             /* remap the flag */ \
             flag = (*ait).second; \
             } \
           else if (dait != deprecatedLongFlagAliasMap.end()) \
             { \
             std::cout << "Long flag \"" << flag << "\" is deprecated. Please use long flag \"" << (*dait).second << "\" instead. " << std::endl; \
             /* remap the flag */ \
             flag = (*dait).second; \
             } \
           } \
         const bool isMultiple = multipleFlags.find(flag) != multipleFlags.end(); \
         const bool isBoolean = std::find(nonbooleanFlags.begin(), nonbooleanFlags.end(), flag) == nonbooleanFlags.end(); \
         dvOptionnalArgsIt = std::find(deserializedVectorFlaggedArgs.begin(), deserializedVectorFlaggedArgs.end(), flag); \
         const bool isPresentVFA = dvOptionnalArgsIt != deserializedVectorFlaggedArgs.end(); \
         if (isBoolean) \
           { \
           /*Ignore if boolean and already present*/ \
           /*Otherwise add it*/ \
           if (!isPresentVFA) \
             { \
             deserializedVectorFlaggedArgs.emplace_back(flag); \
             } \
           ++ac; \
           } \
         else if (isMultiple) \
           { \
           auto dvMultipleArgsIt = deserializedMultipleArgsMap.find(flag); \
           const bool isPresentMA = dvMultipleArgsIt != deserializedMultipleArgsMap.end(); \
           /*Ignore if boolean and already present*/ \
           /*Reset/Add the value if first deserialize or not present*/ \
           if (!isPresentMA || !multipleFlags[flag]) \
             { \
             deserializedMultipleArgsMap[flag] = std::vector<std::string>(); \
             multipleFlags[flag] = true; \
             } \
           ++ac; \
           std::string value; \
           if (ac < static_cast<size_t>(argc)) \
             { \
             value = argv[ac]; \
             ++ac; \
             } \
           deserializedMultipleArgsMap[flag].emplace_back(value); \
           } \
         else \
           { \
           /*Add the flag and if needed*/ \
           if (!isPresentVFA) \
             { \
             deserializedVectorFlaggedArgs.emplace_back(flag); \
             } \
           ++ac; \
           std::string value; \
           if (ac < static_cast<size_t>(argc)) \
             { \
             value = argv[ac]; \
             ++ac; \
             } \
           if (!isPresentVFA) \
             { \
             deserializedVectorFlaggedArgs.emplace_back(value);  \
             } \
           else \
             { \
             *(++dvOptionnalArgsIt) = value; \
             } \
           } \
         } \
       /* short flag case where multiple flags are given at once */ \
       else if (strlen(argv[ac]) > 2 && argv[ac][0]=='-' && argv[ac][1]!='-') \
         { \
         std::string rflag(argv[ac], 1, std::string::npos); \
         for (std::string::size_type fi=0; fi < rflag.size(); ++fi) \
           { \
           std::string tf(rflag, fi, 1); \
           std::string newFlag ="-"; \
           newFlag += tf; \
           auto ait = flagAliasMap.find(newFlag); \
           auto dait = deprecatedFlagAliasMap.find(newFlag); \
           if (ait != flagAliasMap.end()) \
             { \
             /* remap the flag */ \
             newFlag = (*ait).second; \
             } \
           else if (dait != deprecatedFlagAliasMap.end()) \
             { \
             std::cout << "Flag \"" << newFlag << "\" is deprecated. Please use flag \"" << (*dait).second << "\" instead. " << std::endl; \
             /* remap the flag */ \
             newFlag = (*dait).second; \
             } \
           dvOptionnalArgsIt = std::find(deserializedVectorFlaggedArgs.begin(), deserializedVectorFlaggedArgs.end(), newFlag); \
           /*These flags are always boolean, just add it if it's not there already */ \
           if (dvOptionnalArgsIt == deserializedVectorFlaggedArgs.end()) \
             { \
             deserializedVectorFlaggedArgs.emplace_back(newFlag); \
             } \
           } \
         ++ac; \
         } \
       else \
         { \
         /* Replace if needed, otherwise append.*/ \
         if (noFlagCounter < deserializedVectorPositionalArgs.size()) \
           { \
           deserializedVectorPositionalArgs[noFlagCounter] = argv[ac]; \
           } \
         else \
           { \
           deserializedVectorPositionalArgs.emplace_back(argv[ac]); \
           } \
         ++ac; \
         ++noFlagCounter; \
         } \
       } \
 \
    /* Put the now compiled arguments in the argvVector */ \
    std::vector<std::string> argvVector; \
    argvVector.emplace_back(argv[0]); \
    argvVector.insert(argvVector.end(), deserializedVectorFlaggedArgs.begin(), deserializedVectorFlaggedArgs.end()); \
    for (auto & mavit : deserializedMultipleArgsMap) \
      { \
      for (size_t i = 0; i < mavit.second.size(); ++i) \
        { \
        argvVector.emplace_back(mavit.first); \
        argvVector.emplace_back(mavit.second.at(i)); \
        } \
      } \
    argvVector.insert(argvVector.end(), deserializedVectorPositionalArgs.begin(), deserializedVectorPositionalArgs.end()); \
 \
   /* Remap args to a structure that CmdLine::parse() can understand*/ \
   std::vector<char*> vargs; \
   for (ac = 0; ac < argvVector.size(); ++ac) \
     {  \
     vargs.emplace_back(const_cast<char *>(argvVector[ac].c_str())); \
     } \
    commandLine.parse ( static_cast<int>(vargs.size()), (char**) &(vargs[0]) ); \
  } \
catch ( TCLAP::ArgException & e ) \
  { \
  std::cerr << "error: " << e.error() << " for arg " << e.argId() << std::endl; \
  return ( EXIT_FAILURE ); \
  }
#define GENERATE_TCLAP_ASSIGNMENT \
      sigma1 = sigma1Arg.getValue(); \
      sigma2 = sigma2Arg.getValue(); \
      inputVolume = inputVolumeArg.getValue(); \
      outputVolume = outputVolumeArg.getValue(); \
      echoSwitch = echoSwitchArg.getValue(); \
      xmlSwitch = xmlSwitchArg.getValue(); \
      processInformationAddressString = processInformationAddressStringArg.getValue(); \
      returnParameterFile = returnParameterFileArg.getValue(); \

#define GENERATE_TCLAP GENERATE_TCLAP_PARSE;GENERATE_TCLAP_ASSIGNMENT
#define GENERATE_TCLAP_ASSIGNMENT_IFSET \
    if( sigma1Arg.isSet() ) \
      { \
      sigma1 = sigma1Arg.getValue(); \
      } \
    if( sigma2Arg.isSet() ) \
      { \
      sigma2 = sigma2Arg.getValue(); \
      } \
    if( inputVolumeArg.isSet() ) \
      { \
      inputVolume = inputVolumeArg.getValue(); \
      } \
    if( outputVolumeArg.isSet() ) \
      { \
      outputVolume = outputVolumeArg.getValue(); \
      } \
    if( echoSwitchArg.isSet() ) \
      { \
      echoSwitch = echoSwitchArg.getValue(); \
      } \
    if( xmlSwitchArg.isSet() ) \
      { \
      xmlSwitch = xmlSwitchArg.getValue(); \
      } \
    if( processInformationAddressStringArg.isSet() ) \
      { \
      processInformationAddressString = processInformationAddressStringArg.getValue(); \
      } \
    if( returnParameterFileArg.isSet() ) \
      { \
      returnParameterFile = returnParameterFileArg.getValue(); \
      } \

#define GENERATE_ECHOARGS \
if (echoSwitch) \
{ \
std::cout << "Command Line Arguments" << std::endl; \
std::cout << "    sigma1: " << sigma1 << std::endl; \
std::cout << "    sigma2: " << sigma2 << std::endl; \
std::cout << "    inputVolume: " << inputVolume << std::endl; \
std::cout << "    outputVolume: " << outputVolume << std::endl; \
std::cout << "    echoSwitch: " << echoSwitch << std::endl; \
std::cout << "    xmlSwitch: " << xmlSwitch << std::endl; \
std::cout << "    processInformationAddressString: " << processInformationAddressString << std::endl; \
std::cout << "    returnParameterFile: " << returnParameterFile << std::endl; \
}
#define GENERATE_ProcessInformationAddressDecoding \
ModuleProcessInformation *CLPProcessInformation = 0; \
if (!processInformationAddressString.empty()) \
{ \
sscanf(processInformationAddressString.c_str(), "%p", &CLPProcessInformation); \
}
#define PARSE_ARGS GENERATE_LOGO;GENERATE_XML;GENERATE_DECLARE;GENERATE_TCLAP;GENERATE_ECHOARGS;GENERATE_ProcessInformationAddressDecoding;static_assert(true, "") /* Used to allow end-of-macro semi-colon */
