
// Command-line usage (generated by SlicerExecutionModel / GenerateCLP):
//   SimpleThreshold_iampartho \
//       --inputVolume  <input.nii.gz>  \
//       --outputVolume <output.nii.gz> \
//       --lowThreshold  <low>          \
//       --highThreshold <high>         \
//       --outsideValue  <outside>      \
//       --insideValue   <inside>
//

#include "SimpleThresholdCLP.h"  // Auto-generated by GENERATECLP from SimpleThreshold.xml

// ITK headers
#include "itkBinaryThresholdImageFilter.h"
#include "itkImage.h"
#include "itkImageFileReader.h"
#include "itkImageFileWriter.h"

int main(int argc, char * argv[])
{
  // ---------------------------------------------------------------------------
  // 1.  Parse command-line arguments.
  //     PARSE_ARGS is a macro defined in SimpleThresholdCLP.h.
  //     After this call, every <n> tag from the XML becomes a local C++ variable.
  //     E.g.  inputVolume, outputVolume, lowThreshold, highThreshold,
  //           outsideValue, insideValue
  // ---------------------------------------------------------------------------
  PARSE_ARGS;

  // ---------------------------------------------------------------------------
  // 2.  Define image types.
  //     The assignment states the input is a 3D signed-short NIFTI image.
  //     We keep the same pixel type for the output (signed short) so that
  //     the Hounsfield-unit range is preserved.
  // ---------------------------------------------------------------------------
  constexpr unsigned int Dimension = 3;
  using PixelType  = short;                              // signed 16-bit integer
  using ImageType  = itk::Image<PixelType, Dimension>;

  // ---------------------------------------------------------------------------
  // 3.  Read the input image.
  // ---------------------------------------------------------------------------
  using ReaderType = itk::ImageFileReader<ImageType>;
  auto reader = ReaderType::New();
  reader->SetFileName(inputVolume);

  try
  {
    reader->Update();
  }
  catch (const itk::ExceptionObject & err)
  {
    std::cerr << "ERROR: Could not read input file: " << inputVolume << "\n"
              << err << std::endl;
    return EXIT_FAILURE;
  }

  // ---------------------------------------------------------------------------
  // 4.  Set up and run the BinaryThresholdImageFilter.
  //
  //     itk::BinaryThresholdImageFilter classifies each pixel as:
  //       - "inside"  if pixel value is in [lowerThreshold, upperThreshold]
  //       - "outside" otherwise
  //     and replaces the pixel with insideValue or outsideValue respectively.
  //
  //     The filter uses the *same* input and output pixel type (short), so the
  //     inside/outside values we pass in are cast to short as well.
  // ---------------------------------------------------------------------------
  using FilterType = itk::BinaryThresholdImageFilter<ImageType, ImageType>;
  auto filter = FilterType::New();

  filter->SetInput(reader->GetOutput());
  filter->SetLowerThreshold(static_cast<PixelType>(lowThreshold));
  filter->SetUpperThreshold(static_cast<PixelType>(highThreshold));
  filter->SetOutsideValue(static_cast<PixelType>(outsideValue));
  filter->SetInsideValue(static_cast<PixelType>(insideValue));

  // ---------------------------------------------------------------------------
  // 5.  Write the output image.
  // ---------------------------------------------------------------------------
  using WriterType = itk::ImageFileWriter<ImageType>;
  auto writer = WriterType::New();
  writer->SetFileName(outputVolume);
  writer->SetInput(filter->GetOutput());

  try
  {
    writer->Update();
  }
  catch (const itk::ExceptionObject & err)
  {
    std::cerr << "ERROR: Could not write output file: " << outputVolume << "\n"
              << err << std::endl;
    return EXIT_FAILURE;
  }

  std::cout << "SimpleThreshold complete.\n"
            << "  Input  : " << inputVolume  << "\n"
            << "  Output : " << outputVolume << "\n"
            << "  Range  : [" << lowThreshold << ", " << highThreshold << "]\n"
            << "  Inside : " << insideValue  << "\n"
            << "  Outside: " << outsideValue << std::endl;

  return EXIT_SUCCESS;
}
